language: node_js
sudo: false
cache:
  directories:
    - node_modules
    - system-tests/node_modules
notifications:
  webhooks:
    - https://webhooks.gitter.im/e/d763493612da45967361
matrix:
  include:
    - node_js: '6'
      script: npm run lint && npm run flow
    - node_js: '6'
      script: cd system-tests && npm i && cd - && npm run test-system
    - node_js:
        - '7'
        - '6'
        - '4'
      script: npm run test
